### ISSUE TITLE
add support for taints

### ISSUE THREAD

**Issue by m-yosefpor** [openshift-kni/node-label-operator#13]
Being able to define taints on nodes which match a selector. for example:

```
apiVersion: node-labels.openshift.io/v1beta1
kind: Labels
metadata:
  name: taint-sample1
spec:
  nodeNamePatterns:
    - infra-.*
  labels:
    test.openshift.io/foo1: bar1
  taints:
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
``` 

There is another node label operator (https://github.com/barpilot/node-labeler-operator) which seems to be deprecated (no activity since 2018), however it supports defining taints on nodes, based on a selector. Also that operator does not support regex name matching. I think it's really useful to have that feature in this operator as well.
